version: "3.9"
services:
  modbusserver:
    build:
      context: ./modbus-device
    ports:
      - "502:502"
  linux_agent:
    build:
      context: ./linux-agent
      args:
        BASE_URL: "eu-latest.cumulocity.com"
        DEVICE_ID: "asdf1234"
